name: workflow
on:
  schedule:
    - cron: '0 0 * * *' # KST 9:00 AM on everyday
  workflow_dispatch: {}

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Update
        run: |
          npx stargazed -u mooyoul -t ${{ secrets.GH_TOKEN }} -r awesome-stars -m "docs: stargazed update" -s
